### ISSUE TITLE
[DEVA] The joint characters of ल and व are not shown properly

### ISSUE THREAD

**Issue by sudhirb** [pravins/lohit#49]
When half क is followed by व then it is not shown properly by Lohit Devanagari. In the attached image it should be seen as as the one marked in red. But it is seen as the blue highlighted one when we use the Lohit Devenagari font.
![ka va](https://cloud.githubusercontent.com/assets/600020/3103612/93b9356c-e659-11e3-874b-17b7f78ef544.png)

Similarly, when प is followed by ल, similar problem occurs. In the attached image below, it should be seen as the one in yellow but Lohit Devanagari shows it as the one in greyish blue.
![pa la](https://cloud.githubusercontent.com/assets/600020/3103660/6da19a44-e65a-11e3-8e3d-168a545ffd00.png)

**Comment by pravins** [comment]
Resolved this.
References used:

1. http://tdil-dc.in/tdildcMain/articles/82170Devanagari%20Script%20Behaviour%20for%20Hindi%20%20ver%201.4.10.pdf
