### ISSUE TITLE
The word " Drive " is not displaying correctly. Text is overlapping.

### ISSUE THREAD

**Issue by smartvinnu** [pravins/lohit#54]
డ్రైవ్

**Comment by pravins** [comment]
We are working on Lohit Telugu font under lohit2 project. In this we are going to completely rewrite open type tables of Telugu fonts. Requesting you to be on lohit-devel-list@redhat.com and help to test and provide telugu specific inputs. Expecting alpha release by end of month.

**Comment by pravins** [comment]
Will be available with next release.
