### ISSUE TITLE
The Bengali Rha symbol (U09DD) has the dot misplaced.

### ISSUE THREAD

**Issue by capellsk** [pravins/lohit#58]
![bug](https://cloud.githubusercontent.com/assets/5493630/5327932/9e1b2d38-7d8c-11e4-9d67-9be014e9717f.png)

The dot should be nicely centered.
This bug is present in 2.91.1, and not in 2.5.3.

**Comment by capellsk** [comment]
It would be nice to see this fix released. Is there a 2.91.2 coming?

**Comment by pravins** [comment]
Yes sure. Will do it this week.

**Comment by capellsk** [comment]
Great, thanks!
