### ISSUE TITLE
check ngaodia_vir_kaodia_vir_ssaodia   ngaodia_viramasignodia_kaodia ssaodia(ଷ) viramasignodia(୍)

### ISSUE THREAD

**Issue by pravins** [pravins/lohit#61]
This combination was giving subtable error with makeotf. Chaning it to different OT. Check this rules with alpha release of Lohit Odia.

**Comment by ShilpaGite** [comment]
Rule works with Odia.

![screenshot from 2015-01-30 13 47 34](https://cloud.githubusercontent.com/assets/8446171/5972887/e3891f90-a886-11e4-9a95-73e540a82f27.png)
