### ISSUE TITLE
Integrate etunni/lohit-latin

### ISSUE THREAD

**Issue by davelab6** [pravins/lohit#70]
https://github.com/etunni/lohit-latin :)

**Comment by pravins** [comment]
This has been integrated with Lohit project.  http://pravin-s.blogspot.in/2014/11/next-improved-release-of-lohit.html 

Thanks a lot for same :)  It will be nice if we can repeat same for other Lohit family fonts.

**Comment by davelab6** [comment]
Aha! Please upload releases to https://github.com/pravins/lohit/releases :)

**Comment by pravins** [comment]
Nice :+1: 
I never intentionally added it into releases ;)
Thanks you pointed for it, i will add it there.

**Comment by pravins** [comment]
Closing this. I hope we can add Latin in other Lohit fonts soon.
