### ISSUE TITLE
[GU_IN] U+0ABF have no proper shape

### ISSUE THREAD

**Issue by nileshbandhiya** [pravins/lohit#75]
While typing મિ or ધિ (i.e. 0AAE +  0ABF or 0AA7 + 0ABF), it has not actual shape. MATRA should not merge with main character. Here while adding a matra 0ABF (િ) into 0AAE (મ) it joins the character મ. Though, there is little more gap in case of character ધ. The difference can understood easily at attached image. Also update shape for conjunct character for ક and ત.
![mi-dhi-kta](https://cloud.githubusercontent.com/assets/5889363/10869094/37185aac-80c9-11e5-9918-a47cff6fe5c2.jpg)

**Comment by pravins** [comment]
This is working as expected. Feel free to reopen and provide steps to reproduce.
![Uploading lohit-gujarati.png…]()

**Comment by nileshbandhiya** [comment]
I've tested and compared with other fonts. And I think it should be updated. Hence, I've added the image of comparison with both font with shape. There should be display a gap between base character and MATRA, while in Lohit Gujarat, Charat મ and િ    combined as with no gap.

**Comment by pravins** [comment]
Aha..you created issue for addition of gap. I thought it is for removing
gap :)
Lohit is designed in this way. Comparison font you provided is serif and
lohit is sans-serif.

**Comment by nileshbandhiya** [comment]
I know that comparison done with serif font, but I does not mean to add serif to the Gujarati font. But I wish just gap should be adjusted with nice look. I'm using Lohit Gujarati from more than two years. And I've given many suggestions here, and you have done changes in for that in the past. Thanks for it. I hope this will make Lohit Gujarati more attractive.

**Comment by pravins** [comment]
I will definitely compare with other fonts..though do you have any other
fonts in mind?
Gap is for all the consonants or only with "gha" consonant?
