### ISSUE TITLE
ন + দ + ব no longer has a nice juktokar glyph

### ISSUE THREAD

**Issue by capellsk** [pravins/lohit#76]
The latest version 2.91.3 keeps the ন separate from the দ + ব.
Version 2.91.2 is also wrong, with the small ব too far to the right.

**Comment by pravins** [comment]
Can you provide screenshot of problem?

**Comment by capellsk** [comment]
It seems that I was wrong, the glyph is the same for both 2.91.2 and 2.91.3 as far as I can tell. I think I was mistakenly looking at 2.4.3, which is distributed with Ubuntu.

2.4.3 separates the ন from the দ + ব.
2.91.* has the ব too far to the right.

The attached image shows three glyphs. At the top is the current Lohit 2.91.3 representation of ন + দ + ব (connected by ্). In the middle is the current representation of দ + ব, which is fine. At the bottom is the proposed representation of ন + দ + ব, which is how it's traditionally done. Since connecting the ন with the দ does not change the basic representation of the দ, you can add the ব below it just like you would if the দ was not connected to the ন.

![lohit](https://cloud.githubusercontent.com/assets/5493630/12408887/068ffe9e-be8b-11e5-9608-b426086d4a98.png)

**Comment by pravins** [comment]
Thanks for reporting this issue also fixed issue ন্ধ্ব
Resolves with https://github.com/pravins/lohit/commit/d4c8fa1874d86af3da9fcacacf96640aae2a5e30

**Comment by capellsk** [comment]
Great! Looking forward to the next release.

**Comment by capellsk** [comment]
For the record, I don't love the new glyph. The ব is shaped weird compared to the others in the font. And the connection between the দ and the ব looks very different from দ্ব, where there is a roundness where they meet. If anyone ever brushes up this font it would be great to consider making the conjuncts more harmonious with each other.
![glyphs](https://github.com/pravins/lohit/assets/5493630/3f8af35c-f164-40c6-b587-e4234946e706)
