### ISSUE TITLE
ত + ত + ব no longer has a nice juktokar glyph

### ISSUE THREAD

**Issue by jayantanth** [pravins/lohit#79]
ত + ত + ব no longer has a nice juktokar glyph
![right glyph pdf](https://cloud.githubusercontent.com/assets/1370149/15552618/e3927a5e-22d8-11e6-8a05-6abc2deabb2a.jpg)
, I have checked in Libra office

**Comment by pravins** [comment]
This combination gives me correct results in LibreOffice.
Version: 5.2.6.2
Lohit: lohit-bengali-fonts-2.91.3
![lohit-github-issues](https://cloud.githubusercontent.com/assets/56178/25330022/a3e858a0-28cd-11e7-9c26-3b5ffac90667.png)

**Comment by pravins** [comment]
Works for me.
