### ISSUE TITLE
Misplaced anji glyph in Lohit Bengali

### ISSUE THREAD

**Issue by dscorbett** [pravins/lohit#80]
The glyph for U+0980 BENGALI ANJI is at U+0984 in Lohit Bengali 2.91.3. Lohit Assamese gets it right..

**Comment by pravins** [comment]
Thanks for pointing out this issue. Resolved and will be available with next release.

**Comment by pravins** [comment]
Commit: https://github.com/pravins/lohit/commit/b647abdac901df8e335c7224713c726c03f2b2d2
